// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicTimelineItem,
  DefaultTimelineItemProps,
} from "component/plasmic/shared/PlasmicTimelineItem";

export interface TimelineItemType {
  name: string;
  id: string;
  date: string;
}

interface TimelineItemProps extends DefaultTimelineItemProps {
  name: string;
}

function TimelineItem(props: TimelineItemProps) {
  const { name } = props;
  return <PlasmicTimelineItem name={name} />;
}

export default TimelineItem;
