// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useState } from "react";
import {
  PlasmicProfile,
  DefaultProfileProps,
} from "component/plasmic/shared/PlasmicProfile";
import { withAuthenticationRequired } from "@auth0/auth0-react";

type IsVisible = "postDetails" | "mobileSidebar" | undefined;

interface ProfileProps extends DefaultProfileProps {}

function Profile(props: ProfileProps) {
  const [isVisible, setIsVisible] = useState<IsVisible>(undefined);

  const hasInvite =
    localStorage.getItem("ventureId") && localStorage.getItem("code");

  return (
    <PlasmicProfile
      profileForm={{
        isVisible: isVisible,
        setIsVisible: setIsVisible,
        hasInvite,
      }}
    />
  );
}

export default withAuthenticationRequired(Profile);
