// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicMemberItem,
  DefaultMemberItemProps,
} from "component/plasmic/shared/PlasmicMemberItem";
import { IUser } from "module/interface/user";

interface MemberItemProps extends DefaultMemberItemProps {
  user: IUser;
  handleClick: any;
}

function MemberItem(props: MemberItemProps) {
  const { user, handleClick, ...rest } = props;
  return (
    <PlasmicMemberItem
      photoAvatar={{
        user,
      }}
      iconButton={{
        onClick: handleClick,
      }}
      {...rest}
    />
  );
}

export default MemberItem;
