// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useState, useEffect } from "react";
import {
  PlasmicSidebarItem,
  DefaultSidebarItemProps,
} from "component/plasmic/shared/PlasmicSidebarItem";
import { useHistory } from "react-router-dom";

interface SidebarItemProps extends DefaultSidebarItemProps {
  name: string;
  ventureName: string;
  ventureId: string;
  setHasInput?: any;
  itemType?: "timeline" | "createTimeline" | "ventureCollapsed";
}
function SidebarItem(props: SidebarItemProps) {
  const {
    name,
    ventureId,
    ventureName,
    itemType,
    setHasInput,
    ...rest
  } = props;
  const [isUserOnClick, setIsUserOnClick] = useState(false);
  const history = useHistory();
  const ventureHandle =
    itemType === "timeline"
      ? ventureName?.toLowerCase().replace(/\s/g, "")
      : typeof name === "string"
      ? name?.toLowerCase().replace(/\s/g, "")
      : "";
  const timelineHandle =
    itemType !== "createTimeline" ? name?.toLowerCase().replace(/\s/g, "") : "";

  const link =
    itemType === "timeline"
      ? `/${ventureHandle}/${timelineHandle}/feed`
      : `/${name}/feed`;

  useEffect(() => {
    const handleWindowClick = () => setIsUserOnClick(false);
    if (isUserOnClick) {
      window.addEventListener("click", handleWindowClick);
      window.addEventListener("keydown", handleWindowClick);
    } else {
      window.removeEventListener("click", handleWindowClick);
      window.removeEventListener("keydown", handleWindowClick);
    }
    return () => {
      window.removeEventListener("click", handleWindowClick);
      window.removeEventListener("keydown", handleWindowClick);
    };
  }, [isUserOnClick, setIsUserOnClick]);

  return (
    <PlasmicSidebarItem
      {...rest}
      isUserOnClick={isUserOnClick}
      icon={{
        onClick: (e) => {
          itemType === "timeline" && e.stopPropagation();
        },
      }}
      iconButton={{
        onClick: (event) => {
          event.stopPropagation();
          setIsUserOnClick(!isUserOnClick);
        },
      }}
      onClick={() =>
        itemType !== "createTimeline"
          ? history.push(link)
          : history.push(`/${ventureHandle}/newtimeline`)
      }
      itemType={itemType}
      name={name}
      dropdown={{
        timelineHandle,
        ventureHandle,
        isTimeline: itemType === "timeline" ? true : false,
        setIsUserOnClick,
      }}
    />
  );
}

export default SidebarItem;
