// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicInputText,
  DefaultInputTextProps,
} from "component/plasmic/shared/PlasmicInputText";

interface InputTextProps extends DefaultInputTextProps {
  defaultValue?: any;
  register?: any;
  name?: string;
}

function InputText(props: InputTextProps) {
  const { register, name, defaultValue, ...rest } = props;

  return (
    <PlasmicInputText
      input={{ ref: register, name: name, defaultValue: defaultValue }}
      {...rest}
    />
  );
}

export default InputText;
