// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
PlasmicHeader,
DefaultHeaderProps } from
"component/plasmic/shared/PlasmicHeader";

interface HeaderProps extends DefaultHeaderProps {}

function Header(props: HeaderProps) {
  const { ...rest } = props;
  return <PlasmicHeader {...rest} />;
}

export default Header;