// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useState } from "react";
import {
  PlasmicUpdate,
  DefaultUpdateProps,
} from "component/plasmic/shared/PlasmicUpdate";

interface UpdateProps extends DefaultUpdateProps {}

function Update(props: UpdateProps) {
  const [isFlipped, setIsFlipped] = useState(false);

  return (
    <PlasmicUpdate
      {...props}
      toggleUpdateView={{
        "aria-label": "Toggle View",
        onPress: () => {
          setIsFlipped(!isFlipped);
        },
      }}
      contentContainer={{
        isFlipped: isFlipped,
      }}
    />
  );
}

export default Update;
