// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mTVXT6w3HHjZ4d74q3gB76
// Component: ZvAJESOUhw
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_shared.module.css"; // plasmic-import: mTVXT6w3HHjZ4d74q3gB76/projectcss
import sty from "./PlasmicSelectItem.module.css"; // plasmic-import: ZvAJESOUhw/css

import IconCloseIcon from "./icons/PlasmicIcon__IconClose"; // plasmic-import: FJuvOqJzhV/icon

export type PlasmicSelectItem__VariantMembers = {};
export type PlasmicSelectItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicSelectItem__VariantsArgs;
export const PlasmicSelectItem__VariantProps = new Array<VariantPropType>();

export type PlasmicSelectItem__ArgsType = {};
type ArgPropType = keyof PlasmicSelectItem__ArgsType;
export const PlasmicSelectItem__ArgProps = new Array<ArgPropType>();

export type PlasmicSelectItem__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultSelectItemProps {
  className?: string;
}

function PlasmicSelectItem__RenderFunc(props: {
  variants: PlasmicSelectItem__VariantsArgs;
  args: PlasmicSelectItem__ArgsType;
  overrides: PlasmicSelectItem__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__pzzK)}
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box___0FfK
          )}
        >
          {"Metrics"}
        </div>

        <div className={classNames(defaultcss.all, sty.box__sZdqp)}>
          <IconCloseIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(defaultcss.all, sty.svg)}
            role={"img"}
          />
        </div>
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSelectItem__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSelectItem__VariantsArgs;
    args?: PlasmicSelectItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSelectItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSelectItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSelectItem__ArgProps,
      internalVariantPropNames: PlasmicSelectItem__VariantProps,
    });

    return PlasmicSelectItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSelectItem";
  } else {
    func.displayName = `PlasmicSelectItem.${nodeName}`;
  }
  return func;
}

export const PlasmicSelectItem = Object.assign(
  // Top-level PlasmicSelectItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicSelectItem
    internalVariantProps: PlasmicSelectItem__VariantProps,
    internalArgProps: PlasmicSelectItem__ArgProps,
  }
);

export default PlasmicSelectItem;
/* prettier-ignore-end */
